### ISSUE TITLE
Pr.1: La función `implica` hace doble PM

### ISSUE THREAD

**Issue by andeehr** [Alannahuel21/EstrD2023s1#4]
https://github.com/Alannahuel21/EstrD2023s1/blob/6c0b57a84121df6896b84279391ccb848db90127/TP-1_.hs#L84
Siempre que se pueda resolver una función analizando un único parámetro, es mejor hacerlo así. Analizar más de un parámetro agrega complejidad y permite que sea fácil olvidar casos.

**Comment by Alannahuel21** [comment]
Resuelto
